### ISSUE TITLE
关于「小心签名！」章节的推特账号已注销

### ISSUE THREAD

**Issue by zhejianggaoxiao** [slowmist/Blockchain-dark-forest-selfguard-handbook#14]
> OpenSea 在 2022 年前后出现过数起用户持有的知名 NFT 被盗事件，尤其是 2022.2.20 集中爆发，根本原因在于：
>
> 用户在 OpenSea 授权了 NFT（挂单）。
> 黑客钓鱼拿到用户的相关签名。
> 比较正确的解读可以见这：
>
> https://twitter.com/Nesotual/status/1495223117450551300

<img width="574" alt="image" src="https://user-images.githubusercontent.com/20357400/166681707-f757604f-993a-4945-b142-9611d04271f7.png">

这个账号已注销，如果推文之前有截图保存，建议更换截图

**Comment by evilcos** [comment]
嗯，已知晓

**Comment by zhejianggaoxiao** [comment]
done
